name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *"  # 每天午夜运行一次，可根据需要调整时间
  workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的仓库历史记录

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/x-dr/telegraph-Image.git  # 替换为上游仓库的完整 URL，例如 https://github.com/username/original-repo.git
          git fetch upstream

      - name: Merge upstream main into your fork
        run: |
          git checkout main
          git merge upstream/main

      - name: Push changes to your fork
        run: |
          git push origin main